trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/identity/
pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/identity/
extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: identity
    Artifacts:
    - name: AzureIdentity
      safeName: azureidentity
